apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: # Identifies which other resources should be connected to this resource
    app: second-app # Should match the metadata label of the deployed resource
  ports:
    - protocol: 'TCP'
      port: 80 # The public port
      targetPort: 8080 # What your application is listening on
    # - protocol: 'TCP' # You can add multiple ports
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer